# This is an example user config file. Shown values are guided *examples* only!
# You can use `vt cfg` to add any of the shown values from CLI. See `vt cfg -h`.

[esn_map]
# key map of CDM WVD `SystemID = 'ESN you want to use for that CDM WVD'`
'13701' = 'NFCDCH-02-H46J8TKXWP5E3LUFND3LWV0HECKEVN'  # chromecdm 1610 with Google Chrome Windows ESN, real client ID

# ---------------------------- #
#      Information on ESN      #
# ---------------------------- #
#
# > Identifying an ESN:
#
# WWW-BROWSE        : Fallback (don't use this)
# NFCD              : Browser
# NFCDCH            : Browser Chrome
# NFCDFF            : Browser Firefox
# NFCDOP            : Browser Opera
# NFCDSF            : Browser Safari
# NFCDIE-01         : Browser Internet Explorer
# NFCDIE-02         : Browser Edge
# NFCDIE-03         : Browser Chromium Edge
# NFCDIE-04         : Browser Chromium Edge Mac
# NFCDTS-01         : Browser on some kind of device in a Tesla car
# NFANDROID1        : Android device, up to HD content
# NFANDROID2        : Android device, up to 4K content
# NFAPPL            : Apple device
# NFUWA-001         : Windows 10 UWP (universal-windows-platform) Netflix App
# NFPS3             : Sony PS3 device
# NFVITA            : Sony PlayStation Vita device
#
# > Further identification of Android device ESNs:
#
# -PRV-B-           : Set-top-box
# -PRV-C-           : Chrome OS
# -PRV-P-           : Smartphone
# -PRV-T-           : Tablet
# -PRV-             : Android TV?
#
# Next it will contain "-L3-" if it's an L3 device, possibly only if it's unable to retrieve
# L1 even though it's capable of L1.
#
# > Example ESNs:
#
# WWW-BROWSE-FL87J429R65398Y5PN1R9QAYPMLGDU
# NFCDTS-01-FL87J429R65398Y5PN1R9QAYPMLGDU
# NFUWA-001-DMT46QNHH01MNAHJF9415XFCF9X5YJ
# NFANDROID1-MOTORAOSP=ON=SHAMUS-84BE7ED595DBC71300AC45405DC0BA0FABD9D8ABBF15C7F7685968977FD38C88
# NFANDROID1-PRV-P-SAMSUSM-G950F-7169-0BF9A7BFD181989B39FB8FD4845F4E1A0713D4F8EFB93E183118F21A52D77A7D2
# NFANDROID1-PRV-P-XIAOMMI=9=SE-12034-6EA8A15D39427309D0A97686A1A315C6A0ABFE46BECD14BB740EC56C65168E44
# NFANDROID1-PRV-P-GOOGLPIXEL-6720-6EA8A15D39427309D0A97686A1A315C6A0ABFE46BECD14BB740EC56C65168E72
# NFANDROID1-PRV-T-L3-SONY-G3311-4445-6EA8A15D39427309D0A97686A1A315C6A0ABFE46BECD14BB740EC56C65168E72  [one of the generic l3's]
# NFANDROID1-PRV-P-L3-LGE==NEXUS-5-5199-C9B65BEC72EA99A2CDED82A80CBB59B7578A746BEA4CED78E98E62114D0DBFE0
# NFANDROID1-PRV-P-L3-SAMSUSM-N920G-4445-0FF9C880F70786352021D3A330AB57765263070EB3D5238608DCA67FE7D75D942
# NFANDROID1-PVR-P-MOTORMOTO=X4-7463-08CBC1792B4AC7987DD1D972AA31C316D6EB612076FAA7E2D633E240E07D31E08
# NFANDROID1-PRV-SONYANDROIDTV2017-SONYBRAVIA=4K=GB
# NFANDROID2-PRV-SONYANDROIDTV20154K-SONY=BRAVIA=4K=2015-6027-2AD853C75CB104FCA1D86FE35E778B3F1F78906184DE5081CFA22D92ED1E56E6
# NFANDROID2-PRV-AIRTELHYBRIDSTB-LGE==SH960S-AT-6498-A637C5E932201AC90BB07D3D9F526CEFE310BC3B5FE837F1EF567DD3C3D526A0
# NFANDROID2-PRV-NEXUSPLAYERFUGU-ASUS=NEXUS=PLAYER-5771-DAC74A23CAAC461E004362AD0DB96E845F158A57415C9491E263F458E1E2E5E4
# NFANDROID2-PRV-NEXUSPLAYERFUGU-ASUS=NEXUS=PLAYER-4464-D29337F00DF9802099018C32B72224FB04532A5810F59BF026983CAE6A4A5B2C  [forced l3 by disabled oemcryptolib]
# NFANDROID2-PRV-SHIELDANDROIDTV-NVIDISHIELD=ANDROID=TV-5485-D4D24ABA523EF168874D77EEF136881FFEEEE72B0F594230D4FA05C24C8F756A
# NFANDROID2-PRV-SHIELDANDROIDTV-NVIDIASHIELD=ANDROID=TV  [there's also this but idk what it is]
# NFANDROID2-PRV-VOLVER-MGK000000000000066-613E22D12F61DC5BA0B7D3E8854B89CC-7C347928C5AEE7AC518A2194633CE0CD2BE07D889AAFEF2CCC695DBCBD3E1088
# NFAPPL-02-IPHONE8=4-736EB5005784C5D8F6AC495DEB21B4E6A97E52AA1CCAA572AF8C0E7DCBC21955
# NFAPPL-01-IPAD4=4-24F01EB5F949FA979DA385F026521EF40F26882FD318F01CC68D10A554887E12
# NFAPPL-D1-IPAD3=4-5E466F974D24EA3853A21720C67D64D3DA772EE7C991A01E2F4853FCC732BBEB
# NFAPPL-02-IPHONE7=1-6BA4505AEE94C292946D4601110559A1F1A55C6CB6BCAF29E05456F67C666426
# NFPS3-001-6CDUGNUL8Y7UZUQEJ87JX17VM
# NFVITA-01-6CDUGNUL8Y7UZUQEJ87JX17VM
#
# > Choosing an ESN:
#
# If you're using an L1 CDM with WidevineExchange (--cdm_ke) then you must match the ESN with your CDM, as in
# you can't just use any old ESN, even for similar devices or same brand. The System ID contained within the
# ESN must match the System ID of the CDM.
#
# ESNs that use the System ID's of Generic L3s can be used with any CDM System ID with WidevineExchange (--cdm_ke).
# So if you have no available ESN, but wish to key exchange, use that one.
#
